import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import * as Haptics from 'expo-haptics';
import { Ionicons } from '@expo/vector-icons';
import { colors, spacing } from '../theme';

type ExerciseCard = { name: string; target: string; weight: number; reps: number; rest: number };
const starterExercises: ExerciseCard[] = [
  { name: 'Front squat', target: '4 x 6-8', weight: 70, reps: 8, rest: 90 },
  { name: 'Romanian deadlift', target: '3 x 8-10', weight: 60, reps: 10, rest: 90 },
  { name: 'Hanging knee raise', target: '3 x 12-15', weight: 0, reps: 12, rest: 60 },
];

export function TodayScreen() {
  const [exercises, setExercises] = useState(starterExercises);
  const [completed, setCompleted] = useState<Record<string, number>>({});
  const [timer, setTimer] = useState<number | null>(null);
  useEffect(() => { if (timer === null || timer <= 0) return; const interval = setInterval(() => setTimer((value) => (value && value > 0 ? value - 1 : null)), 1000); return () => clearInterval(interval); }, [timer]);
  useEffect(() => { if (timer === 0) void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); }, [timer]);
  function adjust(index: number, field: 'weight' | 'reps', amount: number) { setExercises((current) => current.map((exercise, exerciseIndex) => exerciseIndex === index ? { ...exercise, [field]: Math.max(0, exercise[field] + amount) } : exercise)); }
  function completeSet(exercise: ExerciseCard) { setCompleted((current) => ({ ...current, [exercise.name]: (current[exercise.name] ?? 0) + 1 })); setTimer(exercise.rest); void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium); }
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={styles.eyebrow}>WEDNESDAY · DAY 01</Text><Text style={styles.title}>Lower body + core</Text></View><View style={styles.streak}><Ionicons name="flame" size={18} color={colors.accent} /><Text style={styles.streakText}>04</Text></View></View>
    {timer !== null && timer > 0 && <View style={styles.timer}><Text style={styles.timerLabel}>CHRONOS</Text><Text style={styles.timerValue}>{Math.floor(timer / 60)}:{String(timer % 60).padStart(2, '0')}</Text><View style={styles.timerActions}><Pressable onPress={() => setTimer(timer + 15)}><Text style={styles.timerButton}>+15 s</Text></Pressable><Pressable onPress={() => setTimer(null)}><Text style={styles.timerButton}>Skip</Text></Pressable></View></View>}
    <View style={styles.sessionMeta}><Text style={styles.metaLabel}>SESSION PROGRESS</Text><Text style={styles.metaValue}>{Object.values(completed).reduce((sum, value) => sum + value, 0)} / 10 sets</Text></View>
    {exercises.map((exercise, index) => <View key={exercise.name} style={styles.card}><View style={styles.cardTop}><View><Text style={styles.exerciseName}>{exercise.name}</Text><Text style={styles.target}>{exercise.target} target · {exercise.rest}s rest</Text></View><Ionicons name="ellipsis-horizontal" size={22} color={colors.muted} /></View><View style={styles.controls}><View><Text style={styles.controlLabel}>WEIGHT</Text><View style={styles.stepper}><Pressable onPress={() => adjust(index, 'weight', -2.5)} style={styles.stepButton}><Text style={styles.stepText}>-</Text></Pressable><Text style={styles.controlValue}>{exercise.weight || 'BW'}<Text style={styles.unit}>{exercise.weight ? ' kg' : ''}</Text></Text><Pressable onPress={() => adjust(index, 'weight', 2.5)} style={styles.stepButton}><Text style={styles.stepText}>+</Text></Pressable></View></View><View><Text style={styles.controlLabel}>REPS</Text><View style={styles.stepper}><Pressable onPress={() => adjust(index, 'reps', -1)} style={styles.stepButton}><Text style={styles.stepText}>-</Text></Pressable><Text style={styles.controlValue}>{exercise.reps}</Text><Pressable onPress={() => adjust(index, 'reps', 1)} style={styles.stepButton}><Text style={styles.stepText}>+</Text></Pressable></View></View></View><Pressable style={styles.completeButton} onPress={() => completeSet(exercise)}><Ionicons name="checkmark-circle" size={22} color={colors.accentDark} /><Text style={styles.completeText}>Complete set {completed[exercise.name] ? `· ${completed[exercise.name]} done` : ''}</Text></Pressable></View>)}
  </ScrollView>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.md, paddingBottom: 40 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: spacing.lg, paddingTop: spacing.sm }, eyebrow: { color: colors.accent, fontSize: 11, fontWeight: '700', letterSpacing: 1 }, title: { color: colors.text, fontSize: 28, fontWeight: '800', marginTop: 8 }, streak: { flexDirection: 'row', gap: 5, alignItems: 'center', backgroundColor: colors.surface, padding: 10, borderRadius: 8 }, streakText: { color: colors.text, fontWeight: '800' }, timer: { backgroundColor: colors.accent, borderRadius: 8, padding: spacing.md, marginBottom: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.md }, timerLabel: { color: colors.accentDark, fontSize: 10, fontWeight: '800' }, timerValue: { color: colors.accentDark, fontSize: 26, fontWeight: '900' }, timerActions: { marginLeft: 'auto', flexDirection: 'row', gap: spacing.md }, timerButton: { color: colors.accentDark, fontWeight: '800' }, sessionMeta: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.sm }, metaLabel: { color: colors.muted, fontSize: 11, fontWeight: '700' }, metaValue: { color: colors.text, fontWeight: '700' }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 8, padding: spacing.md, marginTop: spacing.sm }, cardTop: { flexDirection: 'row', justifyContent: 'space-between' }, exerciseName: { color: colors.text, fontSize: 19, fontWeight: '800' }, target: { color: colors.muted, marginTop: 4, fontSize: 12 }, controls: { flexDirection: 'row', gap: spacing.xl, marginTop: spacing.lg }, controlLabel: { color: colors.muted, fontSize: 10, fontWeight: '700', marginBottom: 6 }, stepper: { flexDirection: 'row', alignItems: 'center', gap: 10 }, stepButton: { width: 34, height: 34, borderRadius: 6, backgroundColor: colors.surfaceMuted, alignItems: 'center', justifyContent: 'center' }, stepText: { color: colors.accent, fontSize: 22 }, controlValue: { minWidth: 50, color: colors.text, fontSize: 20, fontWeight: '800', textAlign: 'center' }, unit: { color: colors.muted, fontSize: 12 }, completeButton: { marginTop: spacing.lg, backgroundColor: colors.accent, borderRadius: 6, minHeight: 46, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 }, completeText: { color: colors.accentDark, fontWeight: '900' },
});